using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnManager : MonoBehaviour
{
    [SerializeField] List<GameObject> carsPrefabs;
    [SerializeField] List<GameObject> powerupPrefabs;

    //Vector3 spawnPosition = new Vector3(-2, 4);

    int rowSize = 5;

    float timerCount = 0;
    float difficulty = 3f;

    

    // Start is called before the first frame update
    void Start()
    {
        // Define the time interval that the spawn occurs.
        // Easy: difficulty / 0.5; Normal: difficulty / 1; Hard: difficulty / 1.5; Very Hard: difficulty / 2;
        difficulty /= GameManager.Instance.DifficultyMode;
    }

    // Update is called once per frame
    void Update()
    {
        SpawnRow(); 
    }

    // Spawn a row of units on "difficulty" time intervals
    void SpawnRow()
    {
        if (Gameplay.Instance.isGameStart)
        {
            timerCount += Time.deltaTime;

            if (timerCount > difficulty)
            {
                string structSpawn = SpawnStructGenerator(rowSize);
                //Debug.Log(structSpawn);
                timerCount = 0;

                SpawnObjects(structSpawn);
            }
        }
    }

    // Generat a struct to spawn a row of units of size "structSize"
    string SpawnStructGenerator(int structSize)
    {
        bool hasEmpty = false;
        int posType;
        int powerupCount = 0;

        string spawnStruct = null;

        for(int i = 0; i < structSize; i++)
        {
            posType = Random.Range(0, 3);
            
            // if there is more than 2 powerups to spawn, change to a car
            if (posType == 2 && powerupCount > 1)
            {
                posType = 1;
            }

            // if there is no empty road the last one is changed to a empty road
            if (i == (structSize - 1) && !hasEmpty)
            {
                posType = 0;
            }
            else
            {
                if(posType == 0)
                {
                    hasEmpty = true;
                }

                if(posType == 2)
                {
                    powerupCount++;
                    hasEmpty = true;
                } 
            }

            spawnStruct += posType;
        }

        return spawnStruct;

    }

    // Use the Struct generated by the "SpawnStructGenerator" to spawn units
    void SpawnObjects(string spawnStruct)
    {
        int index = 0;
        int prefabIndex;

        foreach(char spawnPos in spawnStruct)
        {
            if (spawnPos.ToString().Equals("1"))
            {
                prefabIndex = Random.Range(0, carsPrefabs.Count);
                Instantiate(carsPrefabs[prefabIndex], new Vector3(-2 + index, 4, 0), carsPrefabs[prefabIndex].transform.rotation);
            }
            else if (spawnPos.ToString().Equals("2"))
            {
                prefabIndex = Random.Range(0, powerupPrefabs.Count);
                Instantiate(powerupPrefabs[prefabIndex], new Vector3(-2 + index, 4, 0), powerupPrefabs[prefabIndex].transform.rotation);
            }

            index++;
        }
    }
}
